#!/usr/bin/env python3
"""Build a deterministic include file for cells instantiated by a GL netlist."""

import argparse
import re
from pathlib import Path


CELL_RE = re.compile(r"^\s*(sky130_fd_sc_hd__([A-Za-z0-9_]+))\s+\S+\s*\(")
DRIVE_SUFFIX_RE = re.compile(r"_[0-9]+$")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--netlist", type=Path, required=True)
    parser.add_argument("--library", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    modules: set[tuple[str, str]] = set()
    for line in args.netlist.read_text().splitlines():
        match = CELL_RE.match(line)
        if match:
            module = match.group(1)
            family = DRIVE_SUFFIX_RE.sub("", match.group(2))
            modules.add((module, family))

    includes: list[Path] = []
    missing: list[Path] = []
    for module, family in sorted(modules):
        model = args.library / "cells" / family / f"{module}.v"
        if model.is_file():
            includes.append(model.resolve())
        else:
            missing.append(model)

    if missing:
        formatted = "\n".join(f"  {path}" for path in missing)
        raise SystemExit(f"Missing Sky130 models:\n{formatted}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    contents = [
        "// Generated by scripts/prepare_gl_models.py; do not edit.",
        f"// Source modules: {len(includes)}",
    ]
    contents.extend(f'`include "{path}"' for path in includes)
    args.output.write_text("\n".join(contents) + "\n")
    print(f"Prepared {len(includes)} Sky130 cell wrappers in {args.output}")


if __name__ == "__main__":
    main()
